// Banco de Talentos D&D 3.5
// Cobre PHB, Complete Warrior, Complete Arcane, Complete Divine, Complete Adventurer e outros livros
// Estrutura de efeitos:
//   { tipo, alvo, valor, nota }
// Tipos disponíveis:
//   bonus_save      → alvo: 'fortitude' | 'reflex' | 'will'
//   bonus_initiative
//   bonus_hp        → valor: número de PV extras
//   bonus_slot      → alvo: '0'..'9' (nível de magia), valor: número de slots
//   bonus_turning   → valor: usos extras de Expulsar/Repreender
//   bonus_resource  → alvo: nome do recurso, valor: usos extras
//   bonus_skill     → alvo: nome da perícia, valor: bônus
//   bonus_attack    → alvo: 'ranged' | 'melee' | 'all', valor: bônus
//   bonus_damage    → alvo: 'ranged' | 'melee' | 'all', valor: bônus
//   especial        → nota: descrição do efeito mecânico especial

export const CATEGORIAS_TALENTO = [
  'Geral', 'Guerreiro', 'Metamágico', 'Criação de Item', 'Divino',
  'Psiônico', 'Habilidade de Classe', 'Raça', 'Regional',
]

export const LIVROS_TALENTO = [
  'PHB', 'Complete Warrior', 'Complete Arcane', 'Complete Divine',
  'Complete Adventurer', 'PHB II', 'Tome of Battle', 'Expanded Psionics',
  'Races of the Dragon', 'Miniatures Handbook', 'Dungeonscape',
  'Eberron Campaign Setting', 'Outro',
]

export const TALENTOS_DND35 = [
  // ─────────────────────────────────────────────────────────────────────────
  // PHB — GERAL
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'phb_acrobatic',
    nome: 'Acrobático',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem talento inato para saltar e acrobacia.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Saltar', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Acrobacia', valor: 2 },
    ],
  },
  {
    id: 'phb_agile',
    nome: 'Ágil',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem talento para equilíbrio e escapismo.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Equilíbrio', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Escapar da Prisão', valor: 2 },
    ],
  },
  {
    id: 'phb_alertness',
    nome: 'Alerta',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você está mais atento ao ambiente ao seu redor.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Ouvir', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Observar', valor: 2 },
    ],
  },
  {
    id: 'phb_animal_affinity',
    nome: 'Afinidade com Animais',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem um jeito especial com animais.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Lidar com Animais', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Montar', valor: 2 },
    ],
  },
  {
    id: 'phb_armor_light',
    nome: 'Proficiência com Armaduras Leves',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Use armaduras leves sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_armor_medium',
    nome: 'Proficiência com Armaduras Médias',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Proficiência com Armaduras Leves',
    descricao: 'Use armaduras médias sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_armor_heavy',
    nome: 'Proficiência com Armaduras Pesadas',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Proficiência com Armaduras Médias',
    descricao: 'Use armaduras pesadas sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_athletic',
    nome: 'Atlético',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem talento para escalar e nadar.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Escalar', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Nadar', valor: 2 },
    ],
  },
  {
    id: 'phb_augment_summoning',
    nome: 'Convocar Melhorado',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Conjurar em Combate',
    descricao: 'Cada criatura que você conjura recebe +4 FOR e +4 CON.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Criaturas convocadas ganham +4 FOR e +4 CON' },
    ],
  },
  {
    id: 'phb_blind_fight',
    nome: 'Cega-Luta',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você pode lutar com eficácia mesmo sem enxergar o oponente.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Rerola o dado de acerto em combate cego; o oponente não tem vantagem por invisibilidade' },
    ],
  },
  {
    id: 'phb_brew_potion',
    nome: 'Elaborar Poções',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 3',
    descricao: 'Você pode criar poções mágicas.',
    efeitos: [],
  },
  {
    id: 'phb_cleave',
    nome: 'Abater',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso',
    descricao: 'Se você derrubar um oponente, pode fazer um ataque extra imediatamente.',
    efeitos: [],
  },
  {
    id: 'phb_combat_casting',
    nome: 'Conjurar em Combate',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+4 em testes de Concentração quando conjura na defensiva ou preso.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Concentração (em combate)', valor: 4 },
    ],
  },
  {
    id: 'phb_combat_expertise',
    nome: 'Perícia em Combate',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'INT 13',
    descricao: 'Você pode trocar bônus de ataque por bônus de CA.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Troca até -5 em ataque por +5 na CA por 1 rodada' },
    ],
  },
  {
    id: 'phb_combat_reflexes',
    nome: 'Reflexos em Combate',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: '',
    descricao: 'Você pode realizar ataques de oportunidade adicionais por rodada.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Pode realizar ataques de oportunidade extras = mod DEX; pode atacar durante surpreendido' },
    ],
  },
  {
    id: 'phb_craft_magic_arms',
    nome: 'Elaborar Armas e Armaduras Mágicas',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 5',
    descricao: 'Você pode criar armas e armaduras mágicas.',
    efeitos: [],
  },
  {
    id: 'phb_craft_rod',
    nome: 'Elaborar Bastão',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 9',
    descricao: 'Você pode criar bastões mágicos.',
    efeitos: [],
  },
  {
    id: 'phb_craft_staff',
    nome: 'Elaborar Cajado',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 12',
    descricao: 'Você pode criar cajados mágicos.',
    efeitos: [],
  },
  {
    id: 'phb_craft_wand',
    nome: 'Elaborar Varinha',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 5',
    descricao: 'Você pode criar varinhas mágicas.',
    efeitos: [],
  },
  {
    id: 'phb_craft_wondrous',
    nome: 'Elaborar Item Maravilhoso',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 3',
    descricao: 'Você pode criar itens mágicos maravilhosos.',
    efeitos: [],
  },
  {
    id: 'phb_deceitful',
    nome: 'Enganoso',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem talento para fingimento e disfarce.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Falsificação', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Disfarce', valor: 2 },
    ],
  },
  {
    id: 'phb_deft_hands',
    nome: 'Mãos Habilidosas',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem talento para ladinagem e desarmamento de armadilhas.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Ladinagem', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Desviar Dispositivos', valor: 2 },
    ],
  },
  {
    id: 'phb_diehard',
    nome: 'Resistente',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Resistência',
    descricao: 'Você continua lutando mesmo com PV negativos.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ao chegar a -1 a -9 PV, fica incapacitado mas não inconsciente e pode agir normalmente' },
    ],
  },
  {
    id: 'phb_diligent',
    nome: 'Diligente',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você tem talento para avaliação e escrita.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Avaliação', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Decifrar Escritas', valor: 2 },
    ],
  },
  {
    id: 'phb_dodge',
    nome: 'Esquiva',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13',
    descricao: '+1 de CA contra um oponente designado.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+1 CA contra um alvo designado por rodada' },
    ],
  },
  {
    id: 'phb_empower_spell',
    nome: 'Ampliar Magia',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Variáveis numéricas da magia aumentam em 50%.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 2 níveis acima; variáveis numéricas da magia +50%' },
    ],
  },
  {
    id: 'phb_endurance',
    nome: 'Resistência',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+4 em testes de resistência e perícias relacionadas à fadiga e condições ambientais.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+4 em Fortitude contra fadiga, calor, frio e afogamento; pode dormir de armadura' },
    ],
  },
  {
    id: 'phb_enlarge_spell',
    nome: 'Expandir Magia',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Dobra o alcance da magia.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 1 nível acima; dobra o alcance da magia' },
    ],
  },
  {
    id: 'phb_eschew_materials',
    nome: 'Dispensar Materiais',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Conjure magias sem componentes materiais baratos.',
    efeitos: [],
  },
  {
    id: 'phb_exotic_weapon_prof',
    nome: 'Proficiência com Arma Exótica',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'BAB +1',
    descricao: 'Use uma arma exótica específica sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_extend_spell',
    nome: 'Estender Magia',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Dobra a duração da magia.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 1 nível acima; dobra a duração da magia' },
    ],
  },
  {
    id: 'phb_extra_turning',
    nome: 'Expulsar Extra',
    livro: 'PHB',
    categoria: ['Divino'],
    prerequisitos: 'Habilidade de Expulsar ou Repreender Mortos-Vivos',
    descricao: 'Você pode usar sua habilidade de expulsar mortos-vivos 4 vezes a mais por dia.',
    efeitos: [
      { tipo: 'bonus_turning', alvo: '', valor: 4 },
    ],
  },
  {
    id: 'phb_far_shot',
    nome: 'Tiro Distante',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Tiro em Ponto Branco',
    descricao: 'Aumenta o incremento de alcance de armas de projétil ou arremesso.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Armas de projétil: incremento de alcance x1,5; armas de arremesso: dobra o incremento' },
    ],
  },
  {
    id: 'phb_forge_ring',
    nome: 'Forjar Anel',
    livro: 'PHB',
    categoria: ['Criação de Item'],
    prerequisitos: 'Conjurador nível 12',
    descricao: 'Você pode criar anéis mágicos.',
    efeitos: [],
  },
  {
    id: 'phb_great_cleave',
    nome: 'Abate Amplo',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso, Abater, BAB +4',
    descricao: 'Sem limite de ataques extras de Abater por rodada.',
    efeitos: [],
  },
  {
    id: 'phb_great_fortitude',
    nome: 'Fortitude Elevada',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em todos os testes de Fortitude.',
    efeitos: [
      { tipo: 'bonus_save', alvo: 'fortitude', valor: 2 },
    ],
  },
  {
    id: 'phb_greater_spell_focus',
    nome: 'Foco em Magia Aprimorado',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Foco em Magia (escola escolhida)',
    descricao: '+1 adicional na CD das magias da escola escolhida.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+1 na CD das magias de uma escola específica (cumulativo com Foco em Magia)' },
    ],
  },
  {
    id: 'phb_greater_spell_pen',
    nome: 'Penetração de Magia Aprimorada',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Penetração de Magia',
    descricao: '+2 adicional em testes de penetração de resistência mágica.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+4 total em testes de penetração de RM' },
    ],
  },
  {
    id: 'phb_greater_twf',
    nome: 'Luta com Duas Armas Aprimorada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 19, Luta com Duas Armas Melhorada, Luta com Duas Armas, BAB +11',
    descricao: 'Você pode fazer um terceiro ataque com a arma secundária.',
    efeitos: [],
  },
  {
    id: 'phb_greater_weapon_focus',
    nome: 'Foco em Arma Aprimorado',
    livro: 'PHB',
    categoria: ['Guerreiro'],
    prerequisitos: 'Foco em Arma (arma escolhida), BAB +8, Guerreiro nível 8',
    descricao: '+1 adicional em jogadas de ataque com a arma escolhida.',
    efeitos: [],
  },
  {
    id: 'phb_greater_weapon_spec',
    nome: 'Especialização em Arma Aprimorada',
    livro: 'PHB',
    categoria: ['Guerreiro'],
    prerequisitos: 'Foco em Arma, Especialização em Arma, Foco em Arma Aprimorado, Guerreiro nível 12',
    descricao: '+2 adicional em jogadas de dano com a arma escolhida.',
    efeitos: [],
  },
  {
    id: 'phb_heighten_spell',
    nome: 'Aumentar Magia',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Conjure uma magia em um slot de nível superior, aumentando sua CD.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'A magia é tratada como sendo do nível do slot utilizado para sua CD' },
    ],
  },
  {
    id: 'phb_improved_bull_rush',
    nome: 'Investida Aprimorada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso',
    descricao: '+4 em testes de investida; não provoca ataque de oportunidade ao investir.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Não provoca AoO ao iniciar investida; +4 no teste de investida' },
    ],
  },
  {
    id: 'phb_improved_counterspell',
    nome: 'Contradizer Magia Aprimorado',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Contradiga magias usando qualquer magia da mesma escola.',
    efeitos: [],
  },
  {
    id: 'phb_improved_critical',
    nome: 'Crítico Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com a arma, BAB +8',
    descricao: 'Dobra o margem de ameaça crítica da arma escolhida.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Dobra a margem de ameaça crítica de uma arma específica' },
    ],
  },
  {
    id: 'phb_improved_disarm',
    nome: 'Desarmar Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'INT 13, Perícia em Combate',
    descricao: '+4 em tentativas de desarme; não provoca ataque de oportunidade.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Não provoca AoO ao tentar desarmar; +4 no teste de desarme' },
    ],
  },
  {
    id: 'phb_improved_familiar',
    nome: 'Familiar Aprimorado',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Habilidade de Familiar',
    descricao: 'Você pode obter um familiar de um tipo mais poderoso.',
    efeitos: [],
  },
  {
    id: 'phb_improved_feint',
    nome: 'Fingimento Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'INT 13, Perícia em Combate',
    descricao: 'Pode usar Blefar para fintar como ação de movimento.',
    efeitos: [],
  },
  {
    id: 'phb_improved_grapple',
    nome: 'Agarrar Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, Luta Desarmada Aprimorada',
    descricao: '+4 em testes de agarrar; não provoca ataque de oportunidade.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Não provoca AoO ao iniciar agarrão; +4 no teste de agarrar' },
    ],
  },
  {
    id: 'phb_improved_initiative',
    nome: 'Iniciativa Aprimorada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: '',
    descricao: '+4 em testes de iniciativa.',
    efeitos: [
      { tipo: 'bonus_initiative', alvo: '', valor: 4 },
    ],
  },
  {
    id: 'phb_improved_overrun',
    nome: 'Atropelamento Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso',
    descricao: '+4 em testes de atropelamento; o alvo não pode desviar.',
    efeitos: [],
  },
  {
    id: 'phb_improved_precise_shot',
    nome: 'Tiro Preciso Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 19, Tiro em Ponto Branco, Tiro Preciso, BAB +11',
    descricao: 'Ignore a cobertura parcial e atire entre personagens sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_improved_shield_bash',
    nome: 'Golpe de Escudo Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com Escudo',
    descricao: 'Mantenha o bônus de CA do escudo ao atacar com ele.',
    efeitos: [],
  },
  {
    id: 'phb_improved_sunder',
    nome: 'Destruir Aprimorado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso',
    descricao: '+4 em tentativas de destruir; não provoca ataque de oportunidade.',
    efeitos: [],
  },
  {
    id: 'phb_improved_trip',
    nome: 'Viagem Aprimorada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'INT 13, Perícia em Combate',
    descricao: '+4 em tentativas de viagem; não provoca ataque de oportunidade. Se vencer, pode atacar imediatamente.',
    efeitos: [],
  },
  {
    id: 'phb_improved_twf',
    nome: 'Luta com Duas Armas Melhorada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 17, Luta com Duas Armas, BAB +6',
    descricao: 'Você pode fazer um segundo ataque com a arma secundária.',
    efeitos: [],
  },
  {
    id: 'phb_improved_unarmed',
    nome: 'Luta Desarmada Aprimorada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: '',
    descricao: 'Não provoca ataque de oportunidade ao atacar desarmado; causa dano letal.',
    efeitos: [],
  },
  {
    id: 'phb_investigator',
    nome: 'Investigador',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Reunir Informações e Procurar.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Reunir Informações', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Procurar', valor: 2 },
    ],
  },
  {
    id: 'phb_iron_will',
    nome: 'Vontade de Ferro',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em todos os testes de Vontade.',
    efeitos: [
      { tipo: 'bonus_save', alvo: 'will', valor: 2 },
    ],
  },
  {
    id: 'phb_leadership',
    nome: 'Liderança',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Nível 6',
    descricao: 'Você pode atrair seguidores e um companheiro.',
    efeitos: [],
  },
  {
    id: 'phb_lightning_reflexes',
    nome: 'Reflexos Rápidos',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em todos os testes de Reflexos.',
    efeitos: [
      { tipo: 'bonus_save', alvo: 'reflex', valor: 2 },
    ],
  },
  {
    id: 'phb_magical_aptitude',
    nome: 'Aptidão Mágica',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Uso de Dispositivo Mágico e Identificar.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Uso de Dispositivo Mágico', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Identificar', valor: 2 },
    ],
  },
  {
    id: 'phb_manyshot',
    nome: 'Flechada Múltipla',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 17, Tiro em Ponto Branco, Tiro Rápido, BAB +6',
    descricao: 'Dispare duas ou mais flechas com um ataque.',
    efeitos: [],
  },
  {
    id: 'phb_martial_weapon',
    nome: 'Proficiência com Armas Marciais',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Use todas as armas marciais sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_maximize_spell',
    nome: 'Maximizar Magia',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Todas as variáveis numéricas da magia são máximas.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 3 níveis acima; todas as variáveis numéricas são maximizadas' },
    ],
  },
  {
    id: 'phb_mobility',
    nome: 'Mobilidade',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, Esquiva',
    descricao: '+4 de CA contra ataques de oportunidade.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+4 CA contra ataques de oportunidade provocados por movimento' },
    ],
  },
  {
    id: 'phb_mounted_archery',
    nome: 'Arqueria Montada',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Combate Montado',
    descricao: 'Reduz à metade a penalidade de atirar enquanto montado.',
    efeitos: [],
  },
  {
    id: 'phb_mounted_combat',
    nome: 'Combate Montado',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Montar 1 posto',
    descricao: 'Use Montar para proteger sua montaria de ataques.',
    efeitos: [],
  },
  {
    id: 'phb_multiattack',
    nome: 'Ataque Múltiplo',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '3 ou mais ataques naturais',
    descricao: 'Reduz a penalidade dos ataques naturais secundários.',
    efeitos: [],
  },
  {
    id: 'phb_natural_spell',
    nome: 'Magia Natural',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'SAB 13, Forma Selvagem',
    descricao: 'Conjure magias enquanto estiver em Forma Selvagem.',
    efeitos: [],
  },
  {
    id: 'phb_negotiator',
    nome: 'Negociador',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Diplomacia e Sentido de Rua.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Diplomacia', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Sentido de Rua', valor: 2 },
    ],
  },
  {
    id: 'phb_nimble_fingers',
    nome: 'Dedos Ágeis',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Abrir Fechadura e Prestidigitação.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Abrir Fechadura', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Prestidigitação', valor: 2 },
    ],
  },
  {
    id: 'phb_persuasive',
    nome: 'Persuasivo',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Blefar e Intimidar.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Blefar', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Intimidar', valor: 2 },
    ],
  },
  {
    id: 'phb_point_blank_shot',
    nome: 'Tiro em Ponto Branco',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: '',
    descricao: '+1 em jogadas de ataque e dano com arcos e bestas a até 9m.',
    efeitos: [
      { tipo: 'bonus_attack', alvo: 'ranged_close', valor: 1 },
      { tipo: 'bonus_damage', alvo: 'ranged_close', valor: 1 },
    ],
  },
  {
    id: 'phb_power_attack',
    nome: 'Ataque Poderoso',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'FOR 13',
    descricao: 'Troque bônus de ataque por bônus de dano.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Troca até -5 em ataque por +5 no dano (ou +10 com arma de duas mãos)' },
    ],
  },
  {
    id: 'phb_precise_shot',
    nome: 'Tiro Preciso',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Tiro em Ponto Branco',
    descricao: 'Ataque com arco ou besta sem penalidade de tiro em combate próximo.',
    efeitos: [],
  },
  {
    id: 'phb_quick_draw',
    nome: 'Saque Rápido',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'BAB +1',
    descricao: 'Saque qualquer arma como ação livre.',
    efeitos: [],
  },
  {
    id: 'phb_quicken_spell',
    nome: 'Conjuração Rápida',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Conjure uma magia como ação livre.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 4 níveis acima; a magia é conjurada como ação livre' },
    ],
  },
  {
    id: 'phb_rapid_reload',
    nome: 'Recarga Rápida',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com besta escolhida',
    descricao: 'Recarregue a besta escolhida mais rápido.',
    efeitos: [],
  },
  {
    id: 'phb_rapid_shot',
    nome: 'Tiro Rápido',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, Tiro em Ponto Branco',
    descricao: 'Um ataque adicional a -2 com armas de projétil.',
    efeitos: [],
  },
  {
    id: 'phb_ride_by_attack',
    nome: 'Atacar Enquanto Monta',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Combate Montado',
    descricao: 'Quando carregando enquanto montado, pode se mover antes e depois do ataque.',
    efeitos: [],
  },
  {
    id: 'phb_run',
    nome: 'Correr',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Você corre 5x seu deslocamento (em vez de 4x) e mantém a CA de Destreza.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Velocidade de corrida x5; +4 em Saltar com impulso' },
    ],
  },
  {
    id: 'phb_self_sufficient',
    nome: 'Autossuficiente',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Cura e Sobrevivência.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Cura', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Sobrevivência', valor: 2 },
    ],
  },
  {
    id: 'phb_shield_prof',
    nome: 'Proficiência com Escudo',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Use escudos sem penalidade de conjuração.',
    efeitos: [],
  },
  {
    id: 'phb_shot_on_the_run',
    nome: 'Atirar e Recuar',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, Tiro em Ponto Branco, Mobilidade, Esquiva',
    descricao: 'Ataque com arma de projétil e mova-se antes e depois do ataque.',
    efeitos: [],
  },
  {
    id: 'phb_silent_spell',
    nome: 'Magia Silenciosa',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Conjure a magia sem componente verbal.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 1 nível acima; sem componente verbal' },
    ],
  },
  {
    id: 'phb_simple_weapon',
    nome: 'Proficiência com Armas Simples',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Use todas as armas simples sem penalidade.',
    efeitos: [],
  },
  {
    id: 'phb_skill_focus',
    nome: 'Foco em Perícia',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+3 em uma perícia escolhida.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: '(perícia escolhida)', valor: 3 },
    ],
  },
  {
    id: 'phb_spell_focus',
    nome: 'Foco em Magia',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+1 na CD das magias da escola escolhida.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+1 na CD das magias de uma escola específica' },
    ],
  },
  {
    id: 'phb_spell_mastery',
    nome: 'Domínio de Magia',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Mago nível 1',
    descricao: 'Prepare um número de magias sem seu grimório.',
    efeitos: [],
  },
  {
    id: 'phb_spell_penetration',
    nome: 'Penetração de Magia',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em testes de penetração de resistência mágica.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+2 em testes de penetração de RM' },
    ],
  },
  {
    id: 'phb_spirited_charge',
    nome: 'Cavalaria Espirituosa',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Combate Montado, Atacar Enquanto Monta',
    descricao: 'Dobra o dano ao carregar enquanto montado (triplo com lança).',
    efeitos: [],
  },
  {
    id: 'phb_spring_attack',
    nome: 'Ataque em Movimento',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, Esquiva, Mobilidade, BAB +4',
    descricao: 'Mova-se antes e depois de um ataque único sem provocar AoO.',
    efeitos: [],
  },
  {
    id: 'phb_stealthy',
    nome: 'Furtivo',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+2 em Esconder e Mover em Silêncio.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Esconder', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Mover em Silêncio', valor: 2 },
    ],
  },
  {
    id: 'phb_still_spell',
    nome: 'Magia Imóvel',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Conjure a magia sem componentes somáticos.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 1 nível acima; sem componente somático' },
    ],
  },
  {
    id: 'phb_stunning_fist',
    nome: 'Soco Atordoante',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, SAB 13, Luta Desarmada Aprimorada, BAB +8',
    descricao: 'Aturdoa o alvo com um ataque desarmado bem-sucedido.',
    efeitos: [],
  },
  {
    id: 'phb_toughness',
    nome: 'Resistência Física',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: '+3 em pontos de vida.',
    efeitos: [
      { tipo: 'bonus_hp', alvo: '', valor: 3 },
    ],
  },
  {
    id: 'phb_tower_shield',
    nome: 'Proficiência com Torre de Escudo',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: 'Proficiência com Escudo',
    descricao: 'Use escudos-torre sem penalidades adicionais.',
    efeitos: [],
  },
  {
    id: 'phb_track',
    nome: 'Rastrear',
    livro: 'PHB',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Use Sobrevivência para rastrear criaturas.',
    efeitos: [],
  },
  {
    id: 'phb_trample',
    nome: 'Atropelar',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Combate Montado',
    descricao: 'Enquanto montado, atropele oponentes de tamanho menor.',
    efeitos: [],
  },
  {
    id: 'phb_two_weapon_defense',
    nome: 'Defesa com Duas Armas',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 15, Luta com Duas Armas',
    descricao: '+1 de escudo para CA com duas armas; +2 na posição defensiva.',
    efeitos: [],
  },
  {
    id: 'phb_two_weapon_fighting',
    nome: 'Luta com Duas Armas',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 15',
    descricao: 'Reduz as penalidades de lutar com duas armas.',
    efeitos: [],
  },
  {
    id: 'phb_weapon_finesse',
    nome: 'Fineza com Arma',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'BAB +1',
    descricao: 'Use DES em vez de FOR para ataques com armas leves.',
    efeitos: [],
  },
  {
    id: 'phb_weapon_focus',
    nome: 'Foco em Arma',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com a arma, BAB +1',
    descricao: '+1 em jogadas de ataque com a arma escolhida.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+1 em ataques com uma arma específica' },
    ],
  },
  {
    id: 'phb_weapon_spec',
    nome: 'Especialização em Arma',
    livro: 'PHB',
    categoria: ['Guerreiro'],
    prerequisitos: 'Foco em Arma (arma escolhida), Guerreiro nível 4',
    descricao: '+2 em jogadas de dano com a arma escolhida.',
    efeitos: [],
  },
  {
    id: 'phb_whirlwind_attack',
    nome: 'Ataque em Torbilhão',
    livro: 'PHB',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, INT 13, Esquiva, Mobilidade, Ataque em Movimento, Perícia em Combate, BAB +4',
    descricao: 'Ataque todos os oponentes adjacentes com ação de ataque completa.',
    efeitos: [],
  },
  {
    id: 'phb_widen_spell',
    nome: 'Ampliar Área da Magia',
    livro: 'PHB',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Dobra a área de efeito da magia.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 3 níveis acima; dobra o raio/área de efeito da magia' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // COMPLETE WARRIOR
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cw_battle_casting',
    nome: 'Conjuração em Batalha',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Conjurar em Combate',
    descricao: '+4 em Concentração quando conjura enquanto faz ataque completo.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Concentração (ataque completo)', valor: 4 },
    ],
  },
  {
    id: 'cw_blindsight',
    nome: 'Sentido às Cegas',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Cega-luta, Percepção Aguçada ou habilidade de percepção especial',
    descricao: 'Você pode detectar a presença de criaturas dentro de 1,5m sem enxergar.',
    efeitos: [],
  },
  {
    id: 'cw_combat_brute',
    nome: 'Brutalidade em Combate',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'FOR 15, Ataque Poderoso, Abater, BAB +6',
    descricao: 'Cada vez que derruba um oponente com Abater, ganha +2 em ataques até o fim do turno.',
    efeitos: [],
  },
  {
    id: 'cw_deft_opportunist',
    nome: 'Oportunista Habilidoso',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Reflexos em Combate, Foco em Arma, DES 15, BAB +6',
    descricao: '+4 em ataques de oportunidade.',
    efeitos: [
      { tipo: 'bonus_attack', alvo: 'aoo', valor: 4 },
    ],
  },
  {
    id: 'cw_exotic_shield',
    nome: 'Proficiência com Escudo Exótico',
    livro: 'Complete Warrior',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com Escudo',
    descricao: 'Use um tipo específico de escudo exótico sem penalidade.',
    efeitos: [],
  },
  {
    id: 'cw_extra_rage',
    nome: 'Fúria Extra',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Habilidade de Fúria',
    descricao: 'Você pode usar Fúria 2 vezes adicionais por dia.',
    efeitos: [
      { tipo: 'bonus_resource', alvo: 'Fúria', valor: 2 },
    ],
  },
  {
    id: 'cw_extra_smite',
    nome: 'Golpe Sagrado Extra',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Habilidade de Golpe Sagrado',
    descricao: 'Você pode usar Golpe Sagrado 2 vezes adicionais por dia.',
    efeitos: [
      { tipo: 'bonus_resource', alvo: 'Golpe Sagrado', valor: 2 },
    ],
  },
  {
    id: 'cw_focused_shield',
    nome: 'Escudo Focado',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'Proficiência com Escudo, Golpe de Escudo Aprimorado, BAB +6',
    descricao: '+1 adicional de CA por usar escudo ao lutar defensivamente.',
    efeitos: [],
  },
  {
    id: 'cw_greater_resiliency',
    nome: 'Resiliência Elevada',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Resistência Física',
    descricao: '+3 adicionais em pontos de vida (cumulativo com Resistência Física).',
    efeitos: [
      { tipo: 'bonus_hp', alvo: '', valor: 3 },
    ],
  },
  {
    id: 'cw_ground_fighting',
    nome: 'Luta no Chão',
    livro: 'Complete Warrior',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Agarrar Aprimorado',
    descricao: '-2 em vez de -4 em ataques enquanto no chão; sem penalidade de CA.',
    efeitos: [],
  },
  {
    id: 'cw_hammer_blow',
    nome: 'Golpe de Martelo',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso, Abater, BAB +8',
    descricao: 'Troca todos os ataques em uma rodada por um único golpe que derruba automaticamente.',
    efeitos: [],
  },
  {
    id: 'cw_improved_overland_flight',
    nome: 'Voo em Terra Aprimorado',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Voo',
    descricao: 'Sua velocidade de voo aumenta 50%.',
    efeitos: [],
  },
  {
    id: 'cw_melee_evasion',
    nome: 'Evasão em Combate Corpo-a-Corpo',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'DES 15, Esquiva, Mobilidade, BAB +6',
    descricao: '+1 CA contra oponentes que você designou com Esquiva.',
    efeitos: [],
  },
  {
    id: 'cw_phalanx_fighting',
    nome: 'Luta em Falange',
    livro: 'Complete Warrior',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com Escudo, BAB +1',
    descricao: '+2 em ataque e CA quando adjacente a aliado usando o mesmo talento.',
    efeitos: [],
  },
  {
    id: 'cw_power_lunge',
    nome: 'Impulso Poderoso',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso',
    descricao: 'Ao carregar, aplique Ataque Poderoso dobrado no dano.',
    efeitos: [],
  },
  {
    id: 'cw_quick_reconnoiter',
    nome: 'Reconhecimento Rápido',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'DES 13, Alerta',
    descricao: 'Faça testes de Ouvir, Observar e Procurar uma vez por rodada como ação livre.',
    efeitos: [],
  },
  {
    id: 'cw_roundabout_kick',
    nome: 'Chute Giratório',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'DES 13, Luta Desarmada Aprimorada, Soco Atordoante, BAB +12',
    descricao: 'Após derrubar um oponente, pode atacar outro adjacente imediatamente.',
    efeitos: [],
  },
  {
    id: 'cw_shield_charge',
    nome: 'Carga com Escudo',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'Proficiência com Escudo',
    descricao: 'Ao carregar, pode usar o escudo para atordoar o oponente.',
    efeitos: [],
  },
  {
    id: 'cw_shieldmate',
    nome: 'Companheiro de Escudo',
    livro: 'Complete Warrior',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'Proficiência com Escudo, BAB +3',
    descricao: 'Aliados adjacentes recebem +1 de escudo em CA.',
    efeitos: [],
  },
  {
    id: 'cw_street_fighting',
    nome: 'Luta de Rua',
    livro: 'Complete Warrior',
    categoria: ['Geral'],
    prerequisitos: 'Luta Desarmada Aprimorada, BAB +2',
    descricao: '+1d4 de dano em ataques de oportunidade de ataque desarmado.',
    efeitos: [],
  },
  {
    id: 'cw_superior_expertise',
    nome: 'Perícia Superior em Combate',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'INT 13, Perícia em Combate, BAB +6',
    descricao: 'Troque ataques por CA em incrementos maiores.',
    efeitos: [],
  },
  {
    id: 'cw_tactical_optimizer',
    nome: 'Otimizador Tático',
    livro: 'Complete Warrior',
    categoria: ['Guerreiro'],
    prerequisitos: 'INT 13, Perícia em Combate, BAB +6',
    descricao: 'Ganha um bônus adicional de +1 ao usar ataques com Perícia em Combate.',
    efeitos: [],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // COMPLETE ARCANE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ca_arcane_disciple',
    nome: 'Discípulo Arcano',
    livro: 'Complete Arcane',
    categoria: ['Divino'],
    prerequisitos: 'SAB 13, habilidade de conjurar magias divinas',
    descricao: 'Adiciona as magias de domínio de uma divindade à sua lista de magias e ganha um slot adicional por nível.',
    efeitos: [
      { tipo: 'bonus_slot', alvo: '1', valor: 1 },
      { tipo: 'bonus_slot', alvo: '2', valor: 1 },
      { tipo: 'bonus_slot', alvo: '3', valor: 1 },
      { tipo: 'bonus_slot', alvo: '4', valor: 1 },
      { tipo: 'bonus_slot', alvo: '5', valor: 1 },
      { tipo: 'bonus_slot', alvo: '6', valor: 1 },
      { tipo: 'bonus_slot', alvo: '7', valor: 1 },
      { tipo: 'bonus_slot', alvo: '8', valor: 1 },
      { tipo: 'bonus_slot', alvo: '9', valor: 1 },
    ],
  },
  {
    id: 'ca_chain_spell',
    nome: 'Magia em Corrente',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'A magia salta para alvos adicionais.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 3 níveis acima; afeta até 1d6 alvos adicionais com metade do efeito' },
    ],
  },
  {
    id: 'ca_energy_admixture',
    nome: 'Mistura de Energia',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: 'Substituição de Energia',
    descricao: 'Adicione um segundo tipo de energia à magia.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 4 níveis acima; adiciona outro tipo de energia ao efeito' },
    ],
  },
  {
    id: 'ca_energy_substitution',
    nome: 'Substituição de Energia',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: 'Qualquer outro talento metamágico',
    descricao: 'Substitua o tipo de energia da magia por outro.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Sem custo adicional de slot; muda o tipo de energia da magia' },
    ],
  },
  {
    id: 'ca_extra_slot',
    nome: 'Slot Extra de Magia',
    livro: 'Complete Arcane',
    categoria: ['Geral'],
    prerequisitos: 'Habilidade de conjurar magias',
    descricao: 'Você recebe um slot extra de magia de até o 6º nível.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+1 slot de um nível de magia à sua escolha (até nível 6)' },
    ],
  },
  {
    id: 'ca_fiery_burst',
    nome: 'Explosão de Fogo',
    livro: 'Complete Arcane',
    categoria: ['Geral'],
    prerequisitos: 'Habilidade de conjurar magias de fogo',
    descricao: 'Pode usar uma magia de fogo extra por dia que causa 1d6 por nível do conjurador.',
    efeitos: [],
  },
  {
    id: 'ca_innate_spell',
    nome: 'Magia Inata',
    livro: 'Complete Arcane',
    categoria: ['Geral'],
    prerequisitos: 'Qualquer talento metamágico',
    descricao: 'Converta slots de magia em usos de uma magia específica como habilidade de uso à vontade.',
    efeitos: [],
  },
  {
    id: 'ca_know_imbalance',
    nome: 'Conhecer o Desequilíbrio',
    livro: 'Complete Arcane',
    categoria: ['Geral'],
    prerequisitos: 'Conjurar em Combate',
    descricao: 'Quando lança uma magia, +1 de CA e resistência mágica temporários.',
    efeitos: [],
  },
  {
    id: 'ca_metamagic_school',
    nome: 'Escola Metamágica',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: 'Qualquer talento metamágico',
    descricao: 'Aplique um efeito metamágico à sua escola especializada sem aumentar o slot.',
    efeitos: [],
  },
  {
    id: 'ca_obtain_familiar',
    nome: 'Obter Familiar',
    livro: 'Complete Arcane',
    categoria: ['Geral'],
    prerequisitos: 'Nível 3',
    descricao: 'Obtenha um familiar como se fosse um mago de nível equivalente ao seu.',
    efeitos: [],
  },
  {
    id: 'ca_practiced_spellcaster',
    nome: 'Conjurador Experiente',
    livro: 'Complete Arcane',
    categoria: ['Geral'],
    prerequisitos: 'Concentração 4 postos',
    descricao: 'Seu nível efetivo de conjurador aumenta em até 4 para determinação de efeitos de magia (não para slots).',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+4 no nível efetivo de conjurador para efeitos de magias (não afeta slots)' },
    ],
  },
  {
    id: 'ca_repeat_spell',
    nome: 'Magia Repetida',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'A magia se repete na sua próxima rodada automaticamente.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 2 níveis acima; a magia se repete na rodada seguinte' },
    ],
  },
  {
    id: 'ca_sculpt_spell',
    nome: 'Esculpir Magia',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Modifique a área de efeito da magia.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 1 nível acima; muda a forma da área de efeito' },
    ],
  },
  {
    id: 'ca_sudden_empower',
    nome: 'Ampliar Repentino',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Uma vez por dia, amplie uma magia sem aumentar o slot.',
    efeitos: [],
  },
  {
    id: 'ca_sudden_extend',
    nome: 'Estender Repentino',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Uma vez por dia, estenda uma magia sem aumentar o slot.',
    efeitos: [],
  },
  {
    id: 'ca_sudden_maximize',
    nome: 'Maximizar Repentino',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Uma vez por dia, maximize uma magia sem aumentar o slot.',
    efeitos: [],
  },
  {
    id: 'ca_sudden_silent',
    nome: 'Silenciar Repentino',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Uma vez por dia, silencie uma magia sem aumentar o slot.',
    efeitos: [],
  },
  {
    id: 'ca_sudden_still',
    nome: 'Imobilizar Repentino',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Uma vez por dia, imobilize uma magia sem aumentar o slot.',
    efeitos: [],
  },
  {
    id: 'ca_twin_spell',
    nome: 'Magia Gêmea',
    livro: 'Complete Arcane',
    categoria: ['Metamágico'],
    prerequisitos: '',
    descricao: 'Conjure a magia duas vezes com um único slot.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: 'Ocupa um slot 4 níveis acima; a magia é conjurada duas vezes simultaneamente' },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // COMPLETE DIVINE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cd_domain_devotion',
    nome: 'Devoção ao Domínio',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Conjurar magias divinas com domínio',
    descricao: 'Melhora os poderes de seus domínios.',
    efeitos: [],
  },
  {
    id: 'cd_extra_domain_spell',
    nome: 'Magia de Domínio Extra',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Habilidade de conjurar magias de domínio',
    descricao: '+1 slot de magia de domínio de qualquer nível acessível.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+1 slot de magia de domínio de um nível à sua escolha' },
    ],
  },
  {
    id: 'cd_extra_turning_cd',
    nome: 'Expulsão Extra Aprimorada',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Habilidade de Expulsar ou Repreender Mortos-Vivos, Expulsar Extra',
    descricao: 'Mais 4 usos de Expulsar além do talento base.',
    efeitos: [
      { tipo: 'bonus_turning', alvo: '', valor: 4 },
    ],
  },
  {
    id: 'cd_holy_radiance',
    nome: 'Radiância Sagrada',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Expulsar Mortos-Vivos, Clérigo ou Paladino nível 5',
    descricao: 'Gaste dois usos de Expulsar para emitir uma aura de luz sagrada.',
    efeitos: [],
  },
  {
    id: 'cd_improved_turning',
    nome: 'Expulsar Aprimorado',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Habilidade de Expulsar ou Repreender Mortos-Vivos',
    descricao: '+2 em testes de Expulsar Mortos-Vivos.',
    efeitos: [
      { tipo: 'especial', alvo: '', valor: 0, nota: '+2 em testes de nível de clérigo para determinar o resultado de Expulsar' },
    ],
  },
  {
    id: 'cd_sacred_healing',
    nome: 'Cura Sagrada',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'SAB 13, Expulsar Mortos-Vivos',
    descricao: 'Gaste um uso de Expulsar para curar 1d6 PV por nível de clérigo nos aliados adjacentes.',
    efeitos: [],
  },
  {
    id: 'cd_sanctify_ki_strike',
    nome: 'Santificar Golpe Ki',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Monge nível 10',
    descricao: 'Seu golpe ki é considerado bom-alinhado para superar redução de dano.',
    efeitos: [],
  },
  {
    id: 'cd_spontaneous_healer',
    nome: 'Curador Espontâneo',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Clérigo com acesso a magias de cura',
    descricao: 'Troque qualquer slot preparado por uma magia de cura espontaneamente.',
    efeitos: [],
  },
  {
    id: 'cd_true_believer',
    nome: 'Crente Verdadeiro',
    livro: 'Complete Divine',
    categoria: ['Divino'],
    prerequisitos: 'Adorar uma divindade',
    descricao: 'Uma vez por dia, role novamente um d20 quando estiver perto de um símbolo sagrado da sua divindade.',
    efeitos: [],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // COMPLETE ADVENTURER
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'cadv_acrobatic_strike',
    nome: 'Golpe Acrobático',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Acrobacia 12 postos, Ataque em Movimento',
    descricao: '+4 em ataques após usar Acrobacia para mover pelo espaço de um oponente.',
    efeitos: [],
  },
  {
    id: 'cadv_brachiation',
    nome: 'Locomoção por Braços',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'DES 15, Escalar 8 postos',
    descricao: 'Mova-se pela copa das árvores à velocidade normal.',
    efeitos: [],
  },
  {
    id: 'cadv_city_strider',
    nome: 'Andador Urbano',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'DES 13, Mobilidade',
    descricao: 'Mova-se sem penalidade por terreno difícil urbano.',
    efeitos: [],
  },
  {
    id: 'cadv_combat_intuition',
    nome: 'Intuição de Combate',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Sentido de Rua 5 postos',
    descricao: '+1 em iniciativa e +1 em ataques por conhecer o terreno (área urbana familiar).',
    efeitos: [],
  },
  {
    id: 'cadv_cunning_dodge',
    nome: 'Esquiva Astuta',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'DES 13, INT 13, Esquiva',
    descricao: 'Use INT em vez de DES para bônus de Esquiva.',
    efeitos: [],
  },
  {
    id: 'cadv_daring_outlaw',
    nome: 'Fora-da-Lei Audacioso',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Ladino nível 3, Swashbuckler nível 3',
    descricao: 'Os níveis de Ladino e Swashbuckler se combinam para determinar ataque furtivo.',
    efeitos: [],
  },
  {
    id: 'cadv_escape_artist_feint',
    nome: 'Fingimento por Escapismo',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Escapar da Prisão 8 postos',
    descricao: 'Use Escapar da Prisão para fintar em combate.',
    efeitos: [],
  },
  {
    id: 'cadv_extra_wild_shape',
    nome: 'Forma Selvagem Extra',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Forma Selvagem',
    descricao: 'Você pode usar Forma Selvagem 2 vezes adicionais por dia.',
    efeitos: [
      { tipo: 'bonus_resource', alvo: 'Forma Selvagem', valor: 2 },
    ],
  },
  {
    id: 'cadv_extraordinary_concentration',
    nome: 'Concentração Extraordinária',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Concentração 15 postos, Conjurar em Combate',
    descricao: 'Mantenha magias de concentração como ação livre.',
    efeitos: [],
  },
  {
    id: 'cadv_fast_healing',
    nome: 'Cura Acelerada',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'CON 13, Resistência',
    descricao: 'Uma vez por dia, cure 3 PV como ação padrão.',
    efeitos: [],
  },
  {
    id: 'cadv_improved_skirmish',
    nome: 'Escaramuça Melhorada',
    livro: 'Complete Adventurer',
    categoria: ['Habilidade de Classe'],
    prerequisitos: 'Scout nível 11',
    descricao: 'Melhora os bônus de Escaramuça do Scout.',
    efeitos: [],
  },
  {
    id: 'cadv_quick_change',
    nome: 'Troca Rápida',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Disfarce 9 postos',
    descricao: 'Aplique ou remova um disfarce em uma ação de rodada completa.',
    efeitos: [],
  },
  {
    id: 'cadv_shadowstriking',
    nome: 'Ataque nas Sombras',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Ladino nível 3, Esconder 6 postos',
    descricao: 'Faça um ataque furtivo contra um alvo com quem você não tenha linha de visão clara.',
    efeitos: [],
  },
  {
    id: 'cadv_swift_ambusher',
    nome: 'Emboscador Veloz',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Scout nível 4, Ladino nível 4',
    descricao: 'Combine escaramuça e ataque furtivo em certas condições.',
    efeitos: [],
  },
  {
    id: 'cadv_trap_finding',
    nome: 'Encontrar Armadilhas Avançado',
    livro: 'Complete Adventurer',
    categoria: ['Geral'],
    prerequisitos: 'Procurar 4 postos, Desviar Dispositivos 4 postos',
    descricao: '+2 em Procurar e Desviar Dispositivos armadilhas.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Procurar (armadilhas)', valor: 2 },
      { tipo: 'bonus_skill', alvo: 'Desviar Dispositivos (armadilhas)', valor: 2 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PHB II
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'phb2_brutal_strike',
    nome: 'Golpe Brutal',
    livro: 'PHB II',
    categoria: ['Guerreiro'],
    prerequisitos: 'FOR 13, Ataque Poderoso, BAB +6',
    descricao: 'Causa dano extra e pode enjoar o alvo ao usar Ataque Poderoso.',
    efeitos: [],
  },
  {
    id: 'phb2_cover_magic',
    nome: 'Magia Encoberta',
    livro: 'PHB II',
    categoria: ['Geral'],
    prerequisitos: 'Blefar 8 postos, Conjurar em Combate',
    descricao: 'Disfarce a conjuração como ação mundana com teste de Blefar.',
    efeitos: [],
  },
  {
    id: 'phb2_defensive_sweep',
    nome: 'Varredura Defensiva',
    livro: 'PHB II',
    categoria: ['Guerreiro'],
    prerequisitos: 'FOR 13, Reflexos em Combate, BAB +6',
    descricao: 'Ataques de oportunidade extras contra oponentes que entram na sua área.',
    efeitos: [],
  },
  {
    id: 'phb2_elusive_target',
    nome: 'Alvo Elusivo',
    livro: 'PHB II',
    categoria: ['Guerreiro'],
    prerequisitos: 'DES 15, Esquiva, Mobilidade, BAB +6',
    descricao: 'Dificulta que oponentes se beneficiem de flanquear você.',
    efeitos: [],
  },
  {
    id: 'phb2_extra_music',
    nome: 'Música Extra',
    livro: 'PHB II',
    categoria: ['Habilidade de Classe'],
    prerequisitos: 'Música de Bardo',
    descricao: 'Você pode usar Música de Bardo 4 vezes adicionais por dia.',
    efeitos: [
      { tipo: 'bonus_resource', alvo: 'Inspiração Bárdica', valor: 4 },
    ],
  },
  {
    id: 'phb2_fade_into_violence',
    nome: 'Desvanecer na Violência',
    livro: 'PHB II',
    categoria: ['Geral'],
    prerequisitos: 'Esconder 10 postos',
    descricao: 'Após fazer um ataque, tente se esconder como ação livre.',
    efeitos: [],
  },
  {
    id: 'phb2_lunging_strike',
    nome: 'Ataque Lunático',
    livro: 'PHB II',
    categoria: ['Guerreiro'],
    prerequisitos: 'BAB +4',
    descricao: 'Aumente seu alcance em 1,5m para um ataque ao custo de -2 CA.',
    efeitos: [],
  },
  {
    id: 'phb2_oversized_twf',
    nome: 'Luta com Armas Grandes',
    livro: 'PHB II',
    categoria: ['Geral', 'Guerreiro'],
    prerequisitos: 'DES 13, Luta com Duas Armas',
    descricao: 'Use armas de uma mão na mão secundária sem penalidade adicional.',
    efeitos: [],
  },
  {
    id: 'phb2_tactical_advantage',
    nome: 'Vantagem Tática',
    livro: 'PHB II',
    categoria: ['Guerreiro'],
    prerequisitos: 'INT 13, Perícia em Combate, BAB +4',
    descricao: '+2 em ataque contra oponentes flanqueados.',
    efeitos: [],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TOME OF BATTLE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'tob_adaptive_style',
    nome: 'Estilo Adaptável',
    livro: 'Tome of Battle',
    categoria: ['Geral'],
    prerequisitos: '1 manobra conhecida',
    descricao: 'Recupere todas as manobras gastas como ação padrão.',
    efeitos: [],
  },
  {
    id: 'tob_blade_meditation',
    nome: 'Meditação da Lâmina',
    livro: 'Tome of Battle',
    categoria: ['Geral'],
    prerequisitos: '1 manobra de uma das 9 disciplinas',
    descricao: 'Ganha bônus em uma disciplina de manobras ao meditar.',
    efeitos: [],
  },
  {
    id: 'tob_combat_vigor',
    nome: 'Vigor em Combate',
    livro: 'Tome of Battle',
    categoria: ['Geral'],
    prerequisitos: '1 manobra de postura',
    descricao: 'Recupere PV ao usar uma postura de combate.',
    efeitos: [],
  },
  {
    id: 'tob_crusader_devotion',
    nome: 'Devoção do Cruzado',
    livro: 'Tome of Battle',
    categoria: ['Habilidade de Classe'],
    prerequisitos: 'Crusader nível 3',
    descricao: '+2 em testes de Vontade e bônus em manobras Devoted Spirit.',
    efeitos: [
      { tipo: 'bonus_save', alvo: 'will', valor: 2 },
    ],
  },
  {
    id: 'tob_martial_study',
    nome: 'Estudo Marcial',
    livro: 'Tome of Battle',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Aprenda uma manobra de uma das 9 disciplinas.',
    efeitos: [],
  },
  {
    id: 'tob_martial_stance',
    nome: 'Postura Marcial',
    livro: 'Tome of Battle',
    categoria: ['Geral'],
    prerequisitos: '1 manobra conhecida',
    descricao: 'Aprenda uma postura de combate.',
    efeitos: [],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MINIATURES HANDBOOK
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'mh_improved_rapid_shot',
    nome: 'Tiro Rápido Aprimorado',
    livro: 'Miniatures Handbook',
    categoria: ['Guerreiro'],
    prerequisitos: 'DES 13, Tiro em Ponto Branco, Tiro Rápido, BAB +6',
    descricao: 'Remova a penalidade de -2 do Tiro Rápido.',
    efeitos: [],
  },
  {
    id: 'mh_leader_of_men',
    nome: 'Líder de Homens',
    livro: 'Miniatures Handbook',
    categoria: ['Geral'],
    prerequisitos: 'Carisma 13',
    descricao: '+2 em Diplomacia e um bônus para aliados em combate.',
    efeitos: [
      { tipo: 'bonus_skill', alvo: 'Diplomacia', valor: 2 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // DUNGEONSCAPE
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ds_cunning_knowledge',
    nome: 'Conhecimento Perspicaz',
    livro: 'Dungeonscape',
    categoria: ['Habilidade de Classe'],
    prerequisitos: 'Factotum nível 3',
    descricao: 'Gaste 2 pontos de inspiração para adicionar INT a qualquer jogada.',
    efeitos: [],
  },
  {
    id: 'ds_font_of_inspiration',
    nome: 'Fonte de Inspiração',
    livro: 'Dungeonscape',
    categoria: ['Habilidade de Classe'],
    prerequisitos: 'Factotum nível 1, Inspiração',
    descricao: '+2 pontos de inspiração por dia por vez que você tiver este talento.',
    efeitos: [
      { tipo: 'bonus_resource', alvo: 'Inspiração', valor: 2 },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // RACES OF THE DRAGON
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'rod_dragonfire_adept',
    nome: 'Adepto do Fogo Dracônico',
    livro: 'Races of the Dragon',
    categoria: ['Raça'],
    prerequisitos: 'Herança Dracônica',
    descricao: 'Você pode usar o sopro dracônico mais vezes por dia.',
    efeitos: [
      { tipo: 'bonus_resource', alvo: 'Sopro do Dragão', valor: 1 },
    ],
  },
  {
    id: 'rod_draconic_heritage',
    nome: 'Herança Dracônica',
    livro: 'Races of the Dragon',
    categoria: ['Raça'],
    prerequisitos: 'Feiticeiro nível 1 ou descendência de dragão',
    descricao: 'Você tem sangue dracônico e acesso a poderes dracônicos.',
    efeitos: [],
  },
  {
    id: 'rod_draconic_power',
    nome: 'Poder Dracônico',
    livro: 'Races of the Dragon',
    categoria: ['Raça'],
    prerequisitos: 'Herança Dracônica',
    descricao: '+2 em ataque e dano quando usa habilidades dracônicas.',
    efeitos: [],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // EBERRON CAMPAIGN SETTING
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ecb_action_surge',
    nome: 'Surto de Ação',
    livro: 'Eberron Campaign Setting',
    categoria: ['Geral'],
    prerequisitos: '',
    descricao: 'Gaste um ponto de ação para obter uma ação padrão adicional.',
    efeitos: [],
  },
  {
    id: 'ecb_dragonmark',
    nome: 'Marca do Dragão',
    livro: 'Eberron Campaign Setting',
    categoria: ['Raça'],
    prerequisitos: 'Membro de uma das casas dracônicas',
    descricao: 'Você possui uma Marca do Dragão com poderes mágicos.',
    efeitos: [],
  },
]

// Função auxiliar para buscar talento por ID
export function getTalentoPorId(id) {
  return TALENTOS_DND35.find(t => t.id === id) || null
}

// Formata efeitos para exibição curta em chips
export function formatarEfeito(efeito) {
  switch (efeito.tipo) {
    case 'bonus_save':
      return `+${efeito.valor} ${efeito.alvo === 'fortitude' ? 'Fortitude' : efeito.alvo === 'reflex' ? 'Reflexos' : 'Vontade'}`
    case 'bonus_initiative':
      return `+${efeito.valor} Iniciativa`
    case 'bonus_hp':
      return `+${efeito.valor} PV`
    case 'bonus_slot':
      return `+${efeito.valor} slot nv${efeito.alvo}`
    case 'bonus_turning':
      return `+${efeito.valor} Expulsar`
    case 'bonus_resource':
      return `+${efeito.valor} ${efeito.alvo}`
    case 'bonus_skill':
      return `+${efeito.valor} ${efeito.alvo}`
    case 'bonus_attack':
      return `+${efeito.valor} ataque`
    case 'bonus_damage':
      return `+${efeito.valor} dano`
    case 'especial':
      return efeito.nota?.split(';')[0]?.trim() || 'Especial'
    default:
      return efeito.nota || efeito.tipo
  }
}
